name: teklifim_gelsin
description: Flutter Developer Task

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  lottie: ^1.2.1

  #State Management
  get: ^4.6.1

  #Core Utility
  change_app_package_name: ^1.0.0
  flutter_dotenv: ^5.0.2

  #Network Packages
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/lottie_animations/
    - assets/images/banks/
    - .env
   
  
#QuickSand Font Family
  fonts:
    - family: QuickSand-Bold     
      fonts:
        - asset: assets/fonts/QuickSand/Quicksand-Bold.otf
    - family: QuickSand-Light     
      fonts:
        - asset: assets/fonts/QuickSand/QuickSand-Light.otf
    - family: QuickSand-Regular     
      fonts:
        - asset: assets/fonts/QuickSand/QuickSand-Regular.otf

  


